#!/bin/bash

echo "📋 Portfolio Deployment Scripts Usage"
echo "===================================="
echo ""
echo "🏗️  Build and Push Images Only:"
echo "   ./build-and-push.sh"
echo "   REGISTRY=my-registry:5000 ./build-and-push.sh"
echo "   PLATFORM=linux/arm64 ./build-and-push.sh"
echo ""
echo "🚀 Deploy to Kubernetes:"
echo "   ./deploy-k8s.sh                    # Build and deploy"
echo "   ./deploy-k8s.sh --skip-build       # Deploy with existing images"
echo "   ./deploy-k8s.sh --build            # Force build and deploy"
echo ""
echo "🔧 Environment Variables:"
echo "   DOMAIN=example.com                 # Target domain"
echo "   REGISTRY=192.168.1.123:32000       # Docker registry"
echo "   PLATFORM=linux/amd64               # Target architecture"
echo "   NAMESPACE=portfolio                # Kubernetes namespace"
echo ""
echo "📝 Examples:"
echo "   # Deploy to different domain"
echo "   DOMAIN=mysite.com ./deploy-k8s.sh"
echo ""
echo "   # Use different registry"
echo "   REGISTRY=my-registry:5000 ./deploy-k8s.sh"
echo ""
echo "   # Build for ARM64 (e.g., Raspberry Pi cluster)"
echo "   PLATFORM=linux/arm64 ./build-and-push.sh"
echo ""
echo "   # Quick redeploy without rebuild"
echo "   ./deploy-k8s.sh --skip-build"
echo ""